### ISSUE TITLE
Can you suggest how to use this on ubuntu

### ISSUE THREAD

**Issue by victormarcus** [tachtler/pymilter-InfoMilter#1]
How to use pymilter-InfoMilter on ubuntu? How to install the required dependencies?

**Comment by tachtler** [comment]
Hi kumbhaj,

I'm sorry, but I'm not a Ubuntu user.

Maybe you can use pip to install the required dependecies:

```
ipaddress  1.0.22
log4p      2019.7.13.3
pymilter   1.0.3
```

Greetings
Klaus.
